POINTING_DEVICE_DRIVER = analog_joystick
SRC += lib/oled.c

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS += sh1106_i2c
QUANTUM_PAINTER_DISPLAY_TIMEOUT = 120000

OLED_BRIGHTNESS = 128
OLED_SCROLL_TIMEOUT = 60000
OLED_TIMEOUT=180000

WPM_ENABLE = yes

SRC += oled/oled_setup.c
SRC += oled/luna.c
OPT_DEFS += -DLUNA_ENABLE
SRC += oled/ocean_dream.c
OPT_DEFS += -DOCEAN_DREAM_ENABLE